FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

COPY minihacksaw/ .

RUN chmod +x mvnw
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:17
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]
